/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Nov 19 14:36:57 2016. */

#include "ParamMsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Com_Module_RegParams_fields[6] = {
    PB_FIELD(  1, DOUBLE  , OPTIONAL, STATIC  , FIRST, Com_Module_RegParams, paraP, paraP, 0),
    PB_FIELD(  2, DOUBLE  , OPTIONAL, STATIC  , OTHER, Com_Module_RegParams, paraI, paraP, 0),
    PB_FIELD(  3, DOUBLE  , OPTIONAL, STATIC  , OTHER, Com_Module_RegParams, paraD, paraI, 0),
    PB_FIELD(  4, DOUBLE  , OPTIONAL, STATIC  , OTHER, Com_Module_RegParams, paraVelo, paraD, 0),
    PB_FIELD(  5, DOUBLE  , OPTIONAL, STATIC  , OTHER, Com_Module_RegParams, paraAng, paraVelo, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
