/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Nov 30 14:29:48 2016. */

#include "ParamMsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Com_Module_RegParams_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Com_Module_RegParams, target, target, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Com_Module_RegParams, paraP, target, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Com_Module_RegParams, paraI, paraP, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, Com_Module_RegParams, paraD, paraI, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, Com_Module_RegParams, tgtVal, paraD, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
